# conda env  create --file environmet.yml
name: {{ cookiecutter.project_slug }}
  - anaconda
  - conda-forge
  - defaults
dependencias:
  {% if cookiecutter.project_packages == "All" -%}
  - fs
  - jupyter
  - pathlib 
  {% endif -%}
  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
  {% endif -%}
  - python = {{ cookiecutter.python_version }}
  - pip:
  {% if cookiecutter.project_packages == "All" -%}
  - pyhere
  {% endif -%}